version: "3.9"

services:
  whomami:
    image: containous/whoami
    ports:
      - "8080:80"
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip

networks:
  overlay: